/**
 * refreshUniverse.js
 *
 * Regenerates lib/stockUniverse.ts from the live stockdatas collection.
 * Run with:  node scripts/refreshUniverse.js
 *
 * Criteria: symbol has >= 200 records AND at least one record in the last 7 days.
 * Writes the result directly into the TypeScript source file.
 */

const { MongoClient } = require('mongodb');
const fs = require('fs');
const path = require('path');

require('dotenv').config({ path: path.join(__dirname, '../.env.local') });

const uri = process.env.MONGODB_URI;
if (!uri) { console.error('MONGODB_URI not set in .env.local'); process.exit(1); }

async function main() {
  const client = new MongoClient(uri);
  await client.connect();
  const db = client.db('OP_Portfolio_Dashboard');

  const cutoff = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000);
  const recentSymbols = await db.collection('stockdatas').distinct('symbol', { date: { $gte: cutoff } });

  const wellCovered = await db.collection('stockdatas').aggregate([
    { $match: { symbol: { $in: recentSymbols } } },
    { $group: { _id: '$symbol', count: { $sum: 1 }, stockName: { $first: '$stockName' }, isin: { $first: '$isin' } } },
    { $match: { count: { $gte: 200 } } },
    { $sort:  { _id: 1 } },
  ]).toArray();

  await client.close();

  // Build TypeScript lines
  const lines = wellCovered.map(s => {
    const symbol   = s._id.replace(/'/g, "\\'");
    const isin     = (s.isin || '').replace(/'/g, "\\'");
    const name     = (s.stockName || s._id).replace(/'/g, "\\'");
    return `  { symbol: '${symbol}', isin: '${isin}', name: '${name}', exchange: 'NSE' },`;
  });

  const content = `/**
 * Stock Universe — auto-generated by scripts/refreshUniverse.js
 * Last updated: ${new Date().toISOString()}
 * ${wellCovered.length} symbols with >= 200 records, data within last 7 days.
 */

export interface StockInfo {
  symbol: string;
  isin:   string;
  name:   string;
  exchange: string;
}

export const STOCK_UNIVERSE: StockInfo[] = [
${lines.join('\n')}
];

// De-duplicate (safety net)
const seen = new Set<string>();
const UNIQUE_UNIVERSE = STOCK_UNIVERSE.filter(s => {
  if (seen.has(s.symbol)) return false;
  seen.add(s.symbol);
  return true;
});

export { UNIQUE_UNIVERSE as STOCK_UNIVERSE_DEDUPED };
export const STOCK_SYMBOLS = UNIQUE_UNIVERSE.map(s => s.symbol);
export function getStockInfo(symbol: string) { return UNIQUE_UNIVERSE.find(s => s.symbol === symbol); }
export function getStockIsin(symbol: string) { return UNIQUE_UNIVERSE.find(s => s.symbol === symbol)?.isin; }
`;

  const outPath = path.join(__dirname, '../lib/stockUniverse.ts');
  fs.writeFileSync(outPath, content, 'utf8');
  console.log(`✅ Written ${wellCovered.length} stocks to lib/stockUniverse.ts`);
}

main().catch(err => { console.error(err); process.exit(1); });
